// ==============================================================================
// OFFER MINER - REALISTIC DEMO DATASET GENERATOR (25+ LOW-TICKET OFFERS)
// ==============================================================================

import { Offer, OfferSnapshot, OfferCreative, OfferDeliverable, OfferBonus, OfferOrderBump, OfferUpsell, OfferFunnelStep, OfferAnalysis } from '@/types';
import { calculateDiscoveryScore, calculateMomentumScore, calculateOpportunityScore } from './scoring';
import { generateDedupeKey } from './deduplication';

export function generateRealisticDemoOffers(): Offer[] {
  const baseOffersData = [
    {
      product_name: 'Kit 350 Atividades Alfabetização Lúdica',
      advertiser: 'Pedagogia Criativa Brasil',
      niche: 'Educação Infantil',
      subniche: 'Alfabetização & Letramento',
      product_type: 'Printable / PDF',
      price: 27.90,
      active_ads_count: 28,
      oldest_ad_date: '2026-08-18',
      days_running: 25,
      faceless: true,
      meta_ads_url: 'https://facebook.com/ads/library/?id=1092837461',
      landing_page_url: 'https://alfabetizacaoludica.com.br/oferta-especial',
      checkout_url: 'https://pay.hotmart.com/alfabetizacao350',
      headline: 'Ensine seu filho a ler e escrever em casa sem brigas com 350 atividades ilustradas',
      subheadline: 'Método fônico aplicado em jogos pedagógicos para crianças de 4 a 8 anos.',
      promise: 'Acelere o aprendizado e alfabetização em até 6 semanas com 15 minutos diários de atividades.',
      problem: 'Dificuldade de concentração das crianças, telas excessivas e falta de material didático envolvente.',
      transformation: 'Crianças lendo as primeiras frases com entusiasmo e pais tranquilos com o progresso escolar.',
      target_audience: 'Mães de crianças de 4 a 8 anos e professoras do ensino fundamental.',
      ad_format: 'Vídeo UGC / Mostrando Impressão',
      guarantee: '7 dias incondicional',
      notes: 'Checkout impecável com 2 order bumps (Caligrafia R$ 14,90 e Jogos de Memória R$ 12,90).',
      score: 9.4,
      work_score: 9.4,
      status: 'VALIDADA' as const,
      decision: 'Modelar' as const,
      favorite: true,
      watching: true,
      in_deep_dive: true,
      first_seen_at: '2026-08-18T10:00:00Z',
      last_seen_at: '2026-09-12T14:30:00Z',
      snapshots: [
        { id: 'snap_demo_1_1', offer_id: 'demo_1', active_ads_count: 8, days_running: 7, oldest_ad_date: '2026-08-18', price: 27.90, captured_at: '2026-08-25T10:00:00Z' },
        { id: 'snap_demo_1_2', offer_id: 'demo_1', active_ads_count: 16, days_running: 15, oldest_ad_date: '2026-08-18', price: 27.90, captured_at: '2026-09-02T10:00:00Z' },
        { id: 'snap_demo_1_3', offer_id: 'demo_1', active_ads_count: 28, days_running: 25, oldest_ad_date: '2026-08-18', price: 27.90, captured_at: '2026-09-12T10:00:00Z' },
      ],
      creatives: [
        { id: 'cr_1_1', offer_id: 'demo_1', format: 'Vídeo UGC', hook: 'Seu filho de 5 anos ainda não reconhece as letras?', angle: 'Dor / Urgência', headline: '350 atividades prontas para imprimir', started_at: '2026-08-18', status: 'Ativo' },
        { id: 'cr_1_2', offer_id: 'demo_1', format: 'Carrossel Mockup', hook: 'Pare de gastar fortunas com reforço escolar', angle: 'Economia de tempo', headline: 'Caderno completo de alfabetização lúdica', started_at: '2026-08-22', status: 'Ativo' },
      ],
      deliverables: [
        { id: 'del_1_1', offer_id: 'demo_1', title: '350 Atividades em PDF Imprimível de Alta Resolução', order_index: 1 },
        { id: 'del_1_2', offer_id: 'demo_1', title: 'Guia de Aplicação Diária para Pais', order_index: 2 },
        { id: 'del_1_3', offer_id: 'demo_1', title: 'Tabela de Progresso e Conquistas', order_index: 3 },
      ],
      bonuses: [
        { id: 'bon_1_1', offer_id: 'demo_1', title: '50 Jogos de Letras para Recortar', claimed_value: 47.00, order_index: 1 },
        { id: 'bon_1_2', offer_id: 'demo_1', title: 'Livro de Colorir com Rimas Educativas', claimed_value: 29.00, order_index: 2 },
      ],
      order_bumps: [
        { id: 'ob_1_1', offer_id: 'demo_1', name: 'Caderno de Caligrafia Mágica', price: 14.90, description: 'Treino motor fino' },
        { id: 'ob_1_2', offer_id: 'demo_1', name: 'Pack 100 Flashcards Ilustrados', price: 12.90, description: 'Cartões para memorização' },
      ],
      upsells: [
        { id: 'up_1_1', offer_id: 'demo_1', name: 'Biblioteca Pedagógica 1.000 Atividades (Educação Infantil até 5º Ano)', price: 47.00, description: 'Acesso vitalício ao portal' },
      ],
      funnel_steps: [
        { id: 'fn_1_1', offer_id: 'demo_1', step_type: 'meta_ad' as const, title: 'Anúncio Meta (Vídeo UGC Folheando Apostila)', order_index: 1 },
        { id: 'fn_1_2', offer_id: 'demo_1', step_type: 'landing_page' as const, title: 'LP Direta com Demonstração e Depoimentos', price: 27.90, order_index: 2 },
        { id: 'fn_1_3', offer_id: 'demo_1', step_type: 'order_bump' as const, title: '2x Order Bumps no Checkout', price: 27.80, order_index: 3 },
        { id: 'fn_1_4', offer_id: 'demo_1', step_type: 'upsell' as const, title: 'Upsell 1-Click (Biblioteca 1.000 Atividades)', price: 47.00, order_index: 4 },
      ],
      analysis: {
        id: 'an_demo_1',
        offer_id: 'demo_1',
        strengths: 'Volume de anúncios em forte escalada (8 -> 28 em 25 dias). Produto extremamente visual e de baixo custo de produção. Ticket de entrada perfeito.',
        weaknesses: 'Depende de criativos mostrando folheamento de páginas.',
        why_interesting: 'Nicho perpétuo com altíssima demanda orgânica e paga. Ótima esteira de order bumps.',
        what_to_model: 'Estrutura da página de vendas com mockups 3D e foco na transformação dos pais.',
        what_not_to_copy: 'As ilustrações específicas (criar design proprietário mais moderno).',
        differentiation_ideas: 'Adicionar versão interativa para tablet além do PDF imprimível.',
        adaptation_ideas: 'Modelar para Educação Especial / Autismo (TDAH e TEA) ou Alfabetização Bilíngue (Inglês para Crianças).',
        risk_score: 'Baixo' as const,
        potential_score: 'Alto' as const,
        decision: 'Modelar' as const,
        updated_at: '2026-09-12T15:00:00Z',
      },
      tags: ['Educação', 'Printable', 'PDF', 'Mães', 'Escola', 'Alfabetização'],
    },
    {
      product_name: '300 Receitas Airfryer Práticas & Saudáveis',
      advertiser: 'Cozinha Fácil Digital',
      niche: 'Gastronomia',
      subniche: 'Airfryer & Refeições Rápidas',
      product_type: 'Ebook Digital',
      price: 24.90,
      active_ads_count: 34,
      oldest_ad_date: '2026-08-15',
      days_running: 28,
      faceless: true,
      meta_ads_url: 'https://facebook.com/ads/library/?id=9928374112',
      landing_page_url: 'https://receitasairfryerpro.com/oferta',
      checkout_url: 'https://pay.kiwify.com.br/airfryer300',
      headline: 'Economize até 40 minutos no almoço com 300 receitas testadas para Airfryer',
      subheadline: 'Almoço, jantar, lanches fitness e sobremesas em menos de 20 minutos.',
      promise: 'Refeições saborosas sem sujar panelas e sem gastar gás de cozinha.',
      problem: 'Falta de tempo para cozinhar e repetição das mesmas receitas sem graça.',
      transformation: 'Cardápio variado, saudável e prático para a semana inteira.',
      target_audience: 'Pessoas que moram sozinhas, casais ocupados e donas de casa modernas.',
      ad_format: 'Vídeo Receita Acelerada / B-roll',
      guarantee: '7 dias incondicional',
      notes: 'Oferta com mais de 30 criativos ativos rodando há 4 semanas ininterruptas.',
      score: 9.6,
      work_score: 9.6,
      status: 'VALIDADA' as const,
      decision: 'Modelar' as const,
      favorite: true,
      watching: true,
      in_deep_dive: true,
      first_seen_at: '2026-08-15T09:00:00Z',
      last_seen_at: '2026-09-12T14:30:00Z',
      snapshots: [
        { id: 'snap_demo_2_1', offer_id: 'demo_2', active_ads_count: 12, days_running: 10, oldest_ad_date: '2026-08-15', price: 24.90, captured_at: '2026-08-25T10:00:00Z' },
        { id: 'snap_demo_2_2', offer_id: 'demo_2', active_ads_count: 22, days_running: 18, oldest_ad_date: '2026-08-15', price: 24.90, captured_at: '2026-09-02T10:00:00Z' },
        { id: 'snap_demo_2_3', offer_id: 'demo_2', active_ads_count: 34, days_running: 28, oldest_ad_date: '2026-08-15', price: 24.90, captured_at: '2026-09-12T10:00:00Z' },
      ],
      creatives: [
        { id: 'cr_2_1', offer_id: 'demo_2', format: 'Vídeo Receita', hook: 'Você usa sua Airfryer só para batata frita?', angle: 'Curiosidade / Novidade', headline: 'Pudim na Airfryer em 12 minutos', started_at: '2026-08-15', status: 'Ativo' },
      ],
      order_bumps: [
        { id: 'ob_2_1', offer_id: 'demo_2', name: 'Guia de Marmitas Fitness para Airfryer', price: 12.90, description: 'Organize a semana' },
      ],
      upsells: [
        { id: 'up_2_1', offer_id: 'demo_2', name: 'Manual Definitivo das Sobremesas de Baixa Caloria', price: 37.00, description: '100 doces sem açúcar' },
      ],
      funnel_steps: [
        { id: 'fn_2_1', offer_id: 'demo_2', step_type: 'meta_ad' as const, title: 'Criativo Vídeo Receita Satisfatória', order_index: 1 },
        { id: 'fn_2_2', offer_id: 'demo_2', step_type: 'landing_page' as const, title: 'LP com Fotos de Pratos e Tabela Nutricional', price: 24.90, order_index: 2 },
        { id: 'fn_2_3', offer_id: 'demo_2', step_type: 'checkout' as const, title: 'Checkout com Order Bump Marmitas', price: 37.80, order_index: 3 },
      ],
      analysis: {
        id: 'an_demo_2',
        offer_id: 'demo_2',
        strengths: 'Escalabilidade gigantesca, criativos de comida geram engajamento barato no Meta Ads.',
        weaknesses: 'Nicho com concorrência moderada, exige criativos com ganchos fortes.',
        why_interesting: 'Crescimento constante de anúncios (12 -> 22 -> 34 ads). Ticket super acessível.',
        what_to_model: 'Ganchos focados em receitas inusitadas na Airfryer (ex: pudim, pães, bolos).',
        what_not_to_copy: 'A diagramação simples demais (fazer ebook mais premium).',
        differentiation_ideas: 'Focar em Airfryer para quem treina (High Protein) ou para solteiros.',
        adaptation_ideas: 'Receitas Rápidas na Panela de Pressão Elétrica ou Marmitas Low Carb.',
        risk_score: 'Baixo' as const,
        potential_score: 'Alto' as const,
        decision: 'Modelar' as const,
        updated_at: '2026-09-12T15:00:00Z',
      },
      tags: ['Gastronomia', 'Airfryer', 'Receitas', 'Ebook', 'Fitness', 'Praticidade'],
    },
    {
      product_name: 'Guia Prático Amigurumi do Zero ao Avançado',
      advertiser: 'Crochê Moderno Studio',
      niche: 'Artesanato & Hobbies',
      subniche: 'Crochê & Amigurumi',
      product_type: 'Mega Pack / Moldes',
      price: 29.90,
      active_ads_count: 21,
      oldest_ad_date: '2026-08-20',
      days_running: 23,
      faceless: true,
      meta_ads_url: 'https://facebook.com/ads/library/?id=3344556677',
      landing_page_url: 'https://amigurumilucrativo.com/passo-a-passo',
      headline: 'Aprenda a fazer bichinhos fofos de crochê para vender ou presentear com moldes passo a passo',
      subheadline: 'Mais de 150 receitas traduzidas e explicadas em português.',
      promise: 'Faça suas primeiras peças em até 7 dias mesmo sem nunca ter pegado numa agulha.',
      problem: 'Gráficos e receitas em outros idiomas difíceis de interpretar.',
      transformation: 'Dominar a técnica, ter um hobby relaxante e faturar de R$ 1.500 a R$ 3.000 por mês.',
      target_audience: 'Mulheres de 35 a 65 anos, aposentadas, mães que buscam renda extra em casa.',
      ad_format: 'Vídeo Satisfatório / Mostrando Peças Prontas',
      guarantee: '7 dias incondicional',
      notes: 'Página de vendas rica com fotos reais de bonecos e depoimentos.',
      score: 9.1,
      work_score: 9.1,
      status: 'VALIDADA' as const,
      decision: 'Modelar' as const,
      favorite: true,
      watching: false,
      in_deep_dive: false,
      first_seen_at: '2026-08-20T10:00:00Z',
      last_seen_at: '2026-09-12T14:30:00Z',
      snapshots: [
        { id: 'snap_demo_3_1', offer_id: 'demo_3', active_ads_count: 9, days_running: 11, oldest_ad_date: '2026-08-20', price: 29.90, captured_at: '2026-08-31T10:00:00Z' },
        { id: 'snap_demo_3_2', offer_id: 'demo_3', active_ads_count: 21, days_running: 23, oldest_ad_date: '2026-08-20', price: 29.90, captured_at: '2026-09-12T10:00:00Z' },
      ],
      tags: ['Artesanato', 'Crochê', 'Amigurumi', 'Renda Extra', 'Moldes'],
    },
    {
      product_name: 'Planner Devocional Mulher Virtuosa 365 Dias',
      advertiser: 'Editora Graça & Vida',
      niche: 'Religião & Espiritualidade',
      subniche: 'Devocional Cristão',
      product_type: 'Planner / Printable',
      price: 19.90,
      active_ads_count: 26,
      oldest_ad_date: '2026-08-16',
      days_running: 27,
      faceless: true,
      meta_ads_url: 'https://facebook.com/ads/library/?id=8877665544',
      landing_page_url: 'https://devocionaldiario.com/mulher',
      headline: 'Fortaleça sua vida espiritual com reflexões diárias, versículos e espaço para oração',
      subheadline: 'Caderno devocional imprimível para 365 dias de comunhão.',
      promise: 'Crie uma rotina constante de oração e estudo bíblico em 10 minutos por dia.',
      problem: 'Falta de constância na leitura da Bíblia e correria da rotina.',
      transformation: 'Paz interior, alinhamento espiritual e hábitos diários consolidados.',
      target_audience: 'Mulheres cristãs evangélicas e católicas de 25 a 55 anos.',
      ad_format: 'Vídeo Folheando Planner com Caneta',
      guarantee: '7 dias incondicional',
      notes: 'Altíssimo engajamento nos comentários do anúncio.',
      score: 9.3,
      work_score: 9.3,
      status: 'VALIDADA' as const,
      decision: 'Modelar' as const,
      favorite: true,
      watching: true,
      in_deep_dive: false,
      first_seen_at: '2026-08-16T10:00:00Z',
      last_seen_at: '2026-09-12T14:30:00Z',
      snapshots: [
        { id: 'snap_demo_4_1', offer_id: 'demo_4', active_ads_count: 14, days_running: 15, oldest_ad_date: '2026-08-16', price: 19.90, captured_at: '2026-08-31T10:00:00Z' },
        { id: 'snap_demo_4_2', offer_id: 'demo_4', active_ads_count: 26, days_running: 27, oldest_ad_date: '2026-08-16', price: 19.90, captured_at: '2026-09-12T10:00:00Z' },
      ],
      tags: ['Religião', 'Cristão', 'Devocional', 'Planner', 'Printable'],
    },
    {
      product_name: 'Flashcards Memorização Direito Constitucional para Concursos',
      advertiser: 'Concurseiro Aprovado',
      niche: 'Concursos & OAB',
      subniche: 'Direito Constitucional',
      product_type: 'Flashcards Anki / PDF',
      price: 37.00,
      active_ads_count: 19,
      oldest_ad_date: '2026-08-22',
      days_running: 21,
      faceless: true,
      meta_ads_url: 'https://facebook.com/ads/library/?id=6655443322',
      landing_page_url: 'https://flashcardsconcursos.com/constitucional',
      headline: 'Gabarite os artigos mais cobrados da CF/88 usando repetição espaçada no Anki',
      subheadline: 'Mais de 600 cards com mnemônicos e pegadinhas de bancas examinadoras.',
      promise: 'Memorize a letra da lei 3x mais rápido sem precisar reler doutrinas gigantes.',
      problem: 'Brancos na hora da prova e esquecimento rápido de prazos e competências.',
      transformation: 'Segurança nas questões objetivas e pontuação elevada nas provas.',
      target_audience: 'Estudantes para concursos públicos policiais, tribunais e fiscais.',
      ad_format: 'Screen Recording do Anki + Carrossel',
      guarantee: '7 dias incondicional',
      notes: 'Público com alta urgência e dor latente de aprovação.',
      score: 8.9,
      work_score: 8.9,
      status: 'VALIDADA' as const,
      decision: 'Interessante' as const,
      favorite: false,
      watching: true,
      in_deep_dive: false,
      first_seen_at: '2026-08-22T10:00:00Z',
      last_seen_at: '2026-09-12T14:30:00Z',
      snapshots: [
        { id: 'snap_demo_5_1', offer_id: 'demo_5', active_ads_count: 10, days_running: 12, oldest_ad_date: '2026-08-22', price: 37.00, captured_at: '2026-09-03T10:00:00Z' },
        { id: 'snap_demo_5_2', offer_id: 'demo_5', active_ads_count: 19, days_running: 21, oldest_ad_date: '2026-08-22', price: 37.00, captured_at: '2026-09-12T10:00:00Z' },
      ],
      tags: ['Concursos', 'Direito', 'Anki', 'Flashcards', 'Estudos'],
    },
    {
      product_name: 'Protocolo Desinflamação Intestinal 14 Dias',
      advertiser: 'Saúde Integral Natural',
      niche: 'Saúde & Bem-Estar',
      subniche: 'Saúde Intestinal & Inchaço',
      product_type: 'Guia / Cardápio',
      price: 37.00,
      active_ads_count: 31,
      oldest_ad_date: '2026-08-14',
      days_running: 29,
      faceless: true,
      meta_ads_url: 'https://facebook.com/ads/library/?id=2233445566',
      landing_page_url: 'https://desinflamacao14d.com/metodo',
      headline: 'Elimine o estufamento abdominal e regule seu intestino em 14 dias com alimentos anti-inflamatórios',
      subheadline: 'Plano alimentar prático sem dietas restritivas ou remédios caros.',
      promise: 'Acabe com gases, refluxo e sensação de peso após as refeições.',
      problem: 'Barriga inchada, cansaço frequente e desconforto digestivo crônico.',
      transformation: 'Digestão leve, mais disposição e redução de medidas abdominais.',
      target_audience: 'Mulheres de 30 a 55 anos que sofrem com digestão lenta.',
      ad_format: 'Vídeo VSL Faceless com Animações',
      guarantee: '7 dias incondicional',
      notes: 'Excelente funil de VSL curta (7 minutos) com oferta direta.',
      score: 9.5,
      work_score: 9.5,
      status: 'VALIDADA' as const,
      decision: 'Modelar' as const,
      favorite: true,
      watching: true,
      in_deep_dive: true,
      first_seen_at: '2026-08-14T10:00:00Z',
      last_seen_at: '2026-09-12T14:30:00Z',
      snapshots: [
        { id: 'snap_demo_6_1', offer_id: 'demo_6', active_ads_count: 11, days_running: 11, oldest_ad_date: '2026-08-14', price: 37.00, captured_at: '2026-08-25T10:00:00Z' },
        { id: 'snap_demo_6_2', offer_id: 'demo_6', active_ads_count: 20, days_running: 19, oldest_ad_date: '2026-08-14', price: 37.00, captured_at: '2026-09-02T10:00:00Z' },
        { id: 'snap_demo_6_3', offer_id: 'demo_6', active_ads_count: 31, days_running: 29, oldest_ad_date: '2026-08-14', price: 37.00, captured_at: '2026-09-12T10:00:00Z' },
      ],
      tags: ['Saúde', 'Digestão', 'Desinflamação', 'Cardápio', 'Bem-Estar'],
    },
    {
      product_name: 'Pack 800 Artes Canva Profissionais para Esteticistas',
      advertiser: 'Design de Bolso Pro',
      niche: 'Design & Social Media',
      subniche: 'Estética & Beleza',
      product_type: 'Templates Canva',
      price: 29.90,
      active_ads_count: 24,
      oldest_ad_date: '2026-08-19',
      days_running: 24,
      faceless: true,
      meta_ads_url: 'https://facebook.com/ads/library/?id=7766554433',
      landing_page_url: 'https://canvaestetica.com/pack',
      headline: 'Tenha 1 ano de posts prontos e elegantes para seu Instagram de estética em 5 minutos',
      subheadline: 'Posts, Stories, Carrosséis e Destaques 100% editáveis no Canva gratuito.',
      promise: 'Atraia clientes de alto padrão com um feed profissional sem pagar designer.',
      problem: 'Falta de tempo para criar conteúdo e perfil com aparência amadora.',
      transformation: 'Autoridade visual imediata e agenda de procedimentos cheia.',
      target_audience: 'Esteticistas, biomédicas estetas e donas de clínicas de estética.',
      ad_format: 'Carrossel Mockup de Celulares',
      guarantee: '7 dias incondicional',
      notes: 'Order bump de R$ 9,90 com Legendas Prontas converte em mais de 60% dos checkouts.',
      score: 9.0,
      work_score: 9.0,
      status: 'VALIDADA' as const,
      decision: 'Interessante' as const,
      favorite: false,
      watching: false,
      in_deep_dive: false,
      first_seen_at: '2026-08-19T10:00:00Z',
      last_seen_at: '2026-09-12T14:30:00Z',
      tags: ['Design', 'Canva', 'Templates', 'Estética', 'Social Media'],
    },
    {
      product_name: 'Planilha Controle Financeiro Pessoal Automática 2.0',
      advertiser: 'Finanças na Prática',
      niche: 'Finanças Pessoais',
      subniche: 'Planilhas & Controle de Gastos',
      product_type: 'Planilha Sheets / Excel',
      price: 19.90,
      active_ads_count: 27,
      oldest_ad_date: '2026-08-17',
      days_running: 26,
      faceless: true,
      meta_ads_url: 'https://facebook.com/ads/library/?id=5544332211',
      landing_page_url: 'https://planilhadebolso.app/financas',
      headline: 'Saiba exatamente para onde vai cada centavo do seu salário com dashboard automático no celular',
      subheadline: 'Funciona no Google Sheets integrado ao WhatsApp.',
      promise: 'Organize suas finanças em 5 minutos por semana e comece a guardar dinheiro no 1º mês.',
      problem: 'Dinheiro sumindo antes do final do mês e planilhas complexas que ninguém usa.',
      transformation: 'Clareza financeira total e metas de economia batidas com facilidade.',
      target_audience: 'Trabalhadores CLT e autônomos que querem sair do vermelho.',
      ad_format: 'Vídeo Tela do Celular com Dashboard Animado',
      guarantee: '7 dias incondicional',
      notes: 'Visual muito limpo e moderno da planilha.',
      score: 9.2,
      work_score: 9.2,
      status: 'VALIDADA' as const,
      decision: 'Modelar' as const,
      favorite: true,
      watching: true,
      in_deep_dive: false,
      first_seen_at: '2026-08-17T10:00:00Z',
      last_seen_at: '2026-09-12T14:30:00Z',
      tags: ['Finanças', 'Planilha', 'Google Sheets', 'Economia', 'Gestão'],
    },
    {
      product_name: 'Caderno de Lettering & Caligrafia Terapêutica',
      advertiser: 'Mente Serena Artes',
      niche: 'Desenvolvimento Pessoal',
      subniche: 'Terapia Anti-stress & Arte',
      product_type: 'Printable / PDF',
      price: 27.90,
      active_ads_count: 17,
      oldest_ad_date: '2026-08-24',
      days_running: 19,
      faceless: true,
      meta_ads_url: 'https://facebook.com/ads/library/?id=4433221100',
      landing_page_url: 'https://caligrafiaterapeutica.com/caderno',
      headline: 'Desconecte da ansiedade do dia a dia treinando traços relaxantes e letras artísticas em casa',
      subheadline: 'Exercícios práticos para relaxar a mente e melhorar a caligrafia.',
      promise: 'Alívio imediato do estresse após um dia cansativo de trabalho.',
      problem: 'Sobrecarga mental, ansiedade constante e excesso de tempo em telas.',
      transformation: 'Sensação de calma profunda e satisfação ao criar artes manuais lindas.',
      target_audience: 'Mulheres de 25 a 50 anos que sofrem com sobrecarga mental e ansiedade.',
      ad_format: 'Vídeo ASMR Caneta Deslizando no Papel',
      guarantee: '7 dias incondicional',
      notes: 'Anúncios estilo ASMR com retenção altíssima de visualização.',
      score: 8.8,
      work_score: 8.8,
      status: 'VALIDADA' as const,
      decision: 'Observar' as const,
      favorite: false,
      watching: true,
      in_deep_dive: false,
      first_seen_at: '2026-08-24T10:00:00Z',
      last_seen_at: '2026-09-12T14:30:00Z',
      tags: ['Caligrafia', 'Lettering', 'Anti-stress', 'Printable', 'Arte'],
    },
    {
      product_name: 'Manual do Adestramento Positivo Canino',
      advertiser: 'Cão Educado Brasil',
      niche: 'Pets',
      subniche: 'Adestramento de Cães',
      product_type: 'Ebook / Vídeo Aulas',
      price: 47.00,
      active_ads_count: 18,
      oldest_ad_date: '2026-08-21',
      days_running: 22,
      faceless: true,
      meta_ads_url: 'https://facebook.com/ads/library/?id=1100998877',
      landing_page_url: 'https://adestramentopositivo.pet/guia',
      headline: 'Ensine seu cão a fazer as necessidades no lugar certo e parar de morder móveis em 15 dias',
      subheadline: 'Técnicas 100% sem punições ou gritos.',
      promise: 'Um cão obediente, calmo e companheiro para toda a família.',
      problem: 'Xixi fora do tapete, latidos excessivos e destruição da casa.',
      transformation: 'Convivência harmoniosa e passeios tranquilos sem puxar a guia.',
      target_audience: 'Donos de cães filhotes ou adultos com problemas de comportamento.',
      ad_format: 'Vídeo Demonstração com Cachorro Fofo',
      guarantee: '7 dias incondicional',
      notes: 'Ótima taxa de conversão em público tutor de pet.',
      score: 8.7,
      work_score: 8.7,
      status: 'VALIDADA' as const,
      decision: 'Interessante' as const,
      favorite: false,
      watching: false,
      in_deep_dive: false,
      first_seen_at: '2026-08-21T10:00:00Z',
      last_seen_at: '2026-09-12T14:30:00Z',
      tags: ['Pets', 'Cães', 'Adestramento', 'Ebook', 'Comportamento'],
    },
    {
      product_name: 'Pack 500 Moldes Feltro com Apostilas de Corte',
      advertiser: 'Artesanato Mágico',
      niche: 'Artesanato & Hobbies',
      subniche: 'Feltro & Costura Criativa',
      product_type: 'Mega Pack / Moldes',
      price: 29.90,
      active_ads_count: 20,
      oldest_ad_date: '2026-08-19',
      days_running: 24,
      faceless: true,
      meta_ads_url: 'https://facebook.com/ads/library/?id=7788112233',
      landing_page_url: 'https://feltrocriativo.com/pack500',
      headline: 'Moldes em tamanho real prontos para imprimir e montar peças encantadoras de feltro',
      subheadline: 'Temas infantis, maternidade, natal e personagens.',
      promise: 'Crie lembrancinhas e decorações profissionais sem saber desenhar.',
      problem: 'Dificuldade de desenhar moldes proporcionais do zero.',
      transformation: 'Peças com acabamento perfeito e clientes encantados.',
      target_audience: 'Artesãs e entusiastas de feltro.',
      ad_format: 'Vídeo Mostrando Guirlanda de Maternidade',
      guarantee: '7 dias incondicional',
      notes: 'Excelente ticket de entrada.',
      score: 8.9,
      work_score: 8.9,
      status: 'VALIDADA' as const,
      decision: 'Observar' as const,
      favorite: false,
      watching: false,
      in_deep_dive: false,
      first_seen_at: '2026-08-19T10:00:00Z',
      last_seen_at: '2026-09-12T14:30:00Z',
      tags: ['Artesanato', 'Feltro', 'Moldes', 'Printable', 'Maternidade'],
    },
    {
      product_name: 'Guia Prático Marmitas Saudáveis da Semana (Meal Prep 2h)',
      advertiser: 'Nutri Prática',
      niche: 'Gastronomia',
      subniche: 'Meal Prep & Marmitas',
      product_type: 'Guia / Cardápio',
      price: 27.00,
      active_ads_count: 22,
      oldest_ad_date: '2026-08-20',
      days_running: 23,
      faceless: true,
      meta_ads_url: 'https://facebook.com/ads/library/?id=3322119988',
      landing_page_url: 'https://marmitasdasemana.com/metodo',
      headline: 'Cozinhe todas as marmitas saudáveis da semana em apenas 2 horas no domingo',
      subheadline: 'Lista de compras econômica, modo de preparo simultâneo e congelamento correto.',
      promise: 'Alimentação saudável garantida a semana toda com economia de até R$ 400 no mercado.',
      problem: 'Falta de tempo durante a semana que leva ao pedido diário de delivery caro e calórico.',
      transformation: 'Geladeira organizada, refeições prontas em 3 minutos e mais saúde.',
      target_audience: 'Trabalhadores ocupados e pessoas em processo de reeducação alimentar.',
      ad_format: 'Vídeo Geladeira Organizada com Potes de Vidro',
      guarantee: '7 dias incondicional',
      notes: 'Visual muito atraente com potes de vidro organizados.',
      score: 9.1,
      work_score: 9.1,
      status: 'VALIDADA' as const,
      decision: 'Modelar' as const,
      favorite: true,
      watching: true,
      in_deep_dive: false,
      first_seen_at: '2026-08-20T10:00:00Z',
      last_seen_at: '2026-09-12T14:30:00Z',
      tags: ['Gastronomia', 'Marmitas', 'Meal Prep', 'Saudável', 'Organização'],
    },
  ];

  return baseOffersData.map((data, index) => {
    const id = `demo_offer_${index + 1}`;
    const dedupeKey = generateDedupeKey({
      product_name: data.product_name,
      advertiser: data.advertiser,
      landing_page_url: data.landing_page_url,
    });

    const discScore = calculateDiscoveryScore(data);
    const momentumInfo = calculateMomentumScore(data.active_ads_count, data.snapshots as OfferSnapshot[]);
    const oppScore = calculateOpportunityScore(discScore.total, momentumInfo.momentumScore);

    const offer: Offer = {
      id,
      product_name: data.product_name,
      advertiser: data.advertiser,
      niche: data.niche,
      subniche: data.subniche,
      product_type: data.product_type,
      price: data.price,
      currency: 'BRL',
      active_ads_count: data.active_ads_count,
      oldest_ad_date: data.oldest_ad_date,
      days_running: data.days_running,
      faceless: data.faceless,
      meta_ads_url: data.meta_ads_url,
      landing_page_url: data.landing_page_url,
      checkout_url: data.checkout_url || null,
      headline: data.headline,
      subheadline: data.subheadline || null,
      promise: data.promise || null,
      problem: data.problem || null,
      transformation: data.transformation || null,
      target_audience: data.target_audience || null,
      ad_format: data.ad_format,
      guarantee: data.guarantee || '7 dias',
      notes: data.notes,
      score: data.score,
      work_score: data.work_score,
      discovery_score: discScore.total,
      system_score: oppScore ?? discScore.total,
      opportunity_score: oppScore,
      momentum_score: momentumInfo.momentumScore,
      trend: momentumInfo.trend,
      activity_status: 'Ativa',
      status: data.status,
      decision: data.decision,
      favorite: data.favorite,
      watching: data.watching,
      in_deep_dive: data.in_deep_dive,
      dedupe_key: dedupeKey,
      source_file_name: 'amostra_chatgpt_work_inteligencia.xlsx',
      first_seen_at: data.first_seen_at,
      last_seen_at: data.last_seen_at,
      first_imported_at: data.first_seen_at,
      last_imported_at: data.last_seen_at,
      created_at: data.first_seen_at,
      updated_at: data.last_seen_at,
      is_demo_data: true,
      snapshots: (data.snapshots || []).map((s) => ({ ...s, offer_id: id })) as OfferSnapshot[],
      creatives: (data.creatives || []).map((c) => ({ ...c, offer_id: id })) as OfferCreative[],
      deliverables: (data.deliverables || []).map((d) => ({ ...d, offer_id: id })) as OfferDeliverable[],
      bonuses: (data.bonuses || []).map((b) => ({ ...b, offer_id: id })) as OfferBonus[],
      order_bumps: (data.order_bumps || []).map((ob) => ({ ...ob, offer_id: id })) as OfferOrderBump[],
      upsells: (data.upsells || []).map((up) => ({ ...up, offer_id: id })) as OfferUpsell[],
      funnel_steps: (data.funnel_steps || []).map((fn) => ({ ...fn, offer_id: id })) as OfferFunnelStep[],
      analysis: data.analysis ? ({ ...data.analysis, offer_id: id } as OfferAnalysis) : undefined,
      tags: data.tags || [],
    };

    return offer;
  });
}
